name: Deploy to Render on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Change directory to 'develop' and install dependencies
      - name: Install dependencies
        run: cd Develop && npm install

      # Run build (if needed) and deploy to Render
      - name: Build project
        run: cd Develop && npm run build  # Adjust as per your project structure

      - name: Deploy to Render
        run: render deploy --branch main  # Adjust with the actual Render CLI command

